### ISSUE TITLE
No se puede cambiar de Rol

### ISSUE THREAD

**Issue by jforni** [AESALVA/JavaSports#78]
- En el panel de administración de usuarios no se puede cambiar el rol de los usuarios. Desde mi punto de vista, si yo soy adminstrador, en ese panel debería poder cambiar los roles de los usuarios.
- En el panel de personal administrativo no se puede cambiar el rol de los usuarios. Desde mi punto de vista, si yo soy administrador, en ese panel debería poder cambiar los roles de los usuarios.

**Comment by AESALVA** [comment]
Solucionado. Con una salvedad, se puede modificar los roles de usuario tranquilamente, a excepción de los dos super usuarios creadores de la página que seriamos Valentina y Eduardo. Lo pensamos de esa manera al administrar los usuarios.
