### ISSUE TITLE
No puedo enviar formulario de Contacto

### ISSUE THREAD

**Issue by jforni** [AESALVA/JavaSports#79]
En el formulario de Contáctanos,  una vez completados todos los datos,  me muestra Error al lado de Mensaje, pero no me indica que tipo de error es y no envía el mensaje.
![Untitled presentation](https://user-images.githubusercontent.com/6042663/222431860-b9c97639-5024-498a-b1f0-a333551e34bd.jpg)

**Comment by AESALVA** [comment]
Solucionado. Completados los datos se puede enviar el mail, y los mensajes de error son más interactivos para que el usuario sepa que error es el que esta ocurriendo.
